/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teatro;

import javax.swing.JOptionPane;

/**
 *
 * @author EXITOPC
 */
public class Menu extends javax.swing.JFrame {

   Teatro objlista=new Teatro();
   
   int numeroboletas;
   
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JButton();
        atender = new javax.swing.JButton();
        solicitar = new javax.swing.JButton();
        consultarLista = new javax.swing.JButton();
        listaBoletas = new javax.swing.JButton();
        consultarDocumento = new javax.swing.JButton();
        porcentajeGeneros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Venta boletas");

        numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numero.setText("Numero de boletas");
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        atender.setText("Atender");
        atender.setEnabled(false);
        atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderActionPerformed(evt);
            }
        });

        solicitar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        solicitar.setText("Solcitar turno");
        solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarActionPerformed(evt);
            }
        });

        consultarLista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultarLista.setText("Consultar lista");
        consultarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarListaActionPerformed(evt);
            }
        });

        listaBoletas.setText("Listado de boletas vendidas");
        listaBoletas.setEnabled(false);
        listaBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaBoletasActionPerformed(evt);
            }
        });

        consultarDocumento.setText("Consultar por documento");
        consultarDocumento.setEnabled(false);
        consultarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDocumentoActionPerformed(evt);
            }
        });

        porcentajeGeneros.setText("Porcentajes");
        porcentajeGeneros.setEnabled(false);
        porcentajeGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeGenerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solicitar)
                    .addComponent(consultarLista)
                    .addComponent(numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atender, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaBoletas)
                    .addComponent(porcentajeGeneros))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(numero)
                        .addGap(18, 18, 18)
                        .addComponent(solicitar)
                        .addGap(18, 18, 18)
                        .addComponent(consultarLista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(atender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaBoletas)
                        .addGap(18, 18, 18)
                        .addComponent(consultarDocumento)
                        .addGap(13, 13, 13)
                        .addComponent(porcentajeGeneros)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarActionPerformed


    objlista.solicitarTurno(JOptionPane.showInputDialog(" Nombre "), JOptionPane.showInputDialog(" Documento "), JOptionPane.showInputDialog(" Genero Masculino(M) o Femenino(F)"));
        
    atender.setEnabled(true);
        
        
        
    }//GEN-LAST:event_solicitarActionPerformed

    private void consultarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarListaActionPerformed
    
        objlista.imprimir();
        
        
    }//GEN-LAST:event_consultarListaActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
      
       numeroboletas= Integer.parseInt(JOptionPane.showInputDialog(" Diga el numero de boletas a vender "));
       objlista.numBoletas(numeroboletas);
       numero.setEnabled(false);
        
        
    }//GEN-LAST:event_numeroActionPerformed

    private void atenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderActionPerformed
       
        
        int nuboletas= Integer.parseInt(JOptionPane.showInputDialog(" Diga el numero de boletas a comprar "));
        
        objlista.atender(nuboletas);
        
        listaBoletas.setEnabled(true);
        consultarDocumento.setEnabled(true);
        porcentajeGeneros.setEnabled(true);
        
    }//GEN-LAST:event_atenderActionPerformed

    private void listaBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaBoletasActionPerformed
        objlista.imprimirBoletasVendidas();
    }//GEN-LAST:event_listaBoletasActionPerformed

    private void consultarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDocumentoActionPerformed
        String documento= (JOptionPane.showInputDialog(" Diga el numero de documento "));
        objlista.consultarPorDocumento(documento);
    }//GEN-LAST:event_consultarDocumentoActionPerformed

    private void porcentajeGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeGenerosActionPerformed
        objlista.mostrarGeneros();
    }//GEN-LAST:event_porcentajeGenerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atender;
    private javax.swing.JButton consultarDocumento;
    private javax.swing.JButton consultarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listaBoletas;
    private javax.swing.JButton numero;
    private javax.swing.JButton porcentajeGeneros;
    private javax.swing.JButton solicitar;
    // End of variables declaration//GEN-END:variables
}
